### ISSUE TITLE
Where does Holly View pager fit in

### ISSUE THREAD

**Issue by AkshayChordiya** [florent37/HollyViewPager#1]
Hi, 

This is not really an issue. The library is extremely beautiful & I appreciate your hard work. 
I'm too excited to use it but I want to know where does Holly View Pager fit in the application design. 
It has potential & I'm waiting to use it.

**Comment by florent37** [comment]
It's a good question, I think it'll be usefull if you have to display a lot of information, for example a list of tasks organized by weeks, or a large amount of articles organized by themes

I only provide the UI, don't know all the usages :)

**Comment by AkshayChordiya** [comment]
@florent37 
Thank you for the suggestions. I can understand just that I'm excited to use it but confused. 
I'll close the issue now
